name: Build and Test ğŸš€

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout Code ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Setup Node ğŸ“¦
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install Dependencies ğŸ”§
        run: npm ci

      - name: Test ğŸ§ª
        run: npm run test

      - name: Build Project ğŸ—ï¸
        run: npm run build

      - name: Archive Build Artifacts ğŸ“¦
        uses: actions/upload-artifact@v4
        with:
          name: app-dist
          path: dist

  build-and-deploy-storybook:
    runs-on: ubuntu-latest
    needs: build-and-test
    timeout-minutes: 2

    steps:
      - name: Checkout code ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Setup Node ğŸ“¦
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install Dependencies ğŸ”§
        run: npm ci

      - name: Build Storybook
        run: npm run build-storybook

      - name: Archive Storybook Artifacts ğŸ“¦
        uses: actions/upload-artifact@v4
        with:
          name: storybook-dist
          path: storybook-static/

  deploy-to-gh-pages:
    runs-on: ubuntu-latest
    needs: [build-and-test, build-and-deploy-storybook]
    timeout-minutes: 2
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download Vue App Artifacts
        uses: actions/download-artifact@v4
        with:
          name: app-dist
          path: dist/

      - name: Download Storybook Artifacts
        uses: actions/download-artifact@v4
        with:
          name: storybook-dist
          path: dist/ux/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
